### ISSUE TITLE
SSL unavailable, download links via unsecure HTTP only

### ISSUE THREAD

**Issue by Thireus** [super3/peercoin.net#204]
Please implement SSL with a valid certificate for peercoin.net.

https://peercoin.net

**Comment by Thireus** [comment]
bump

**Comment by Thireus** [comment]
bump

**Comment by Thireus** [comment]
desperate bump... :(

**Comment by TheWildHorse** [comment]
I sent a message to @super3 about this, and if I should implement it. Waiting for feedback. :)

**Comment by sandakersmann** [comment]
Fantastic news! :+1:

**Comment by FuzzyBearBTC** [comment]
@TheWildHorse I would say please go ahead and implement if you have the certificate and access to do so on the server. @super3 seems to be quite busy with other projects, which is not a problem, but should not be a hindrance on such development of peercoin.net

**Comment by Thireus** [comment]
I think I'm gonna bump this thread every month until SSL is implemented if you don't mind. :)

**Comment by Thireus** [comment]
bump

**Comment by TheWildHorse** [comment]
Ok, I'm looking over the certificates to buy.

**Comment by TheWildHorse** [comment]
Sent the info on which cert to buy to @super3, as soon as he buys it, I will implement it on the server.

**Comment by FuzzyBearBTC** [comment]
@TheWildHorse Many thanks :)

**Comment by Thireus** [comment]
Oh, looks like I missed August and September for the monthly "bump".

**Comment by Thireus** [comment]
... and bump for October.

**Comment by D9ping** [comment]
You can use StartCom for free, you just need a valid working postmaster e-mail address to qualify for a free DV-certificate. 
For proper Apache/Nginx  configuration go to: https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by TheWildHorse** [comment]
I am pleased to announce that this has finally been taken care of. A rewrite rule has been added to redirect all traffic to HTTPS and the cert is valid for a year from now.

**Comment by D9ping** [comment]
The rewrite rule broke all links.

**Comment by TheWildHorse** [comment]
Whoops, missed it somehow. Reverted back, working on a hotfix.

**Comment by TheWildHorse** [comment]
Doesn't seem to be the rewrite rule, but the server setup instead.

**Comment by TheWildHorse** [comment]
Hotfix has been applied and the subpages are functional once again, if you notice any other errors please let me know.

**Comment by D9ping** [comment]
There is a mixed content warning because of the css font import in: assest/css/flat-ui.css  on [line 1](https://github.com/super3/peercoin.net/blob/20eb889110642a9d5d39a5713cbcb5fd180c07f8/assets/css/flat-ui.css#L1).

**Comment by TheWildHorse** [comment]
Thank you, I have applied a fix.

**Comment by Thireus** [comment]
Yay! This is good news :).

Next step, fix all the vulnz: https://www.ssllabs.com/ssltest/analyze.html?d=peercoin.net&hideResults=on

**Comment by D9ping** [comment]
Do a system upgrade ASAP:
sudo apt-get update && sudo apt-get upgrade

Edit you peercoin tls/ssl virtualhost with [proper openssl configuration](https://mozilla.github.io/server-side-tls/ssl-config-generator/)

Regenerate new private key, signing request(CSR), and certificate, , because of heartbleed vulnerability you have to consider peercoin webserver ssl private key as comprised..

**Comment by D9ping** [comment]
Do fix the heartbleed vulnerability(CVE-2014-0160) by upgrading openssl. Otherwise using httpS: is currently worse than only using http. This is because if the private key get in wrong hands, anyone with the private key can claims to be the peercoin.net server and your are giving a false sense of security. It's better to tell people it's insecure and let them know it's insecure than it is to tell people you are secure and the connect is in reality not secure at all.

td;lr
If you can't fix it, disable TLS(formally: SSL). 
But this better to fix this by upgrading: openssl as soon as possible, to actually resolve this issue.
